version: 0.2
env:
  variables:
    GO_VERSION: 1.16.5

phases:
  install:
    commands:
      - echo "start installing..."
      - wget https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
      - export PATH="/usr/local/go/bin:$PATH" && export GOPATH="$HOME/go" && export PATH="$GOPATH/bin:$PATH"
  build:
    commands:
      - echo "start building..."
      - GOOS=linux go build -o main
      - zip main.zip main
  post_build:
    commands:
      - echo "Updating function"
      - aws lambda update-function-code --function-name my-first-function --zip-file fileb://main.zip
